### ISSUE TITLE
Ajuda.

### ISSUE THREAD

**Issue by gabilu0** [jpalvesloiola/fj11-contas#1]
Boa noite. João Pedro?...
Estou fazendo o curso també mas não estou conseguindo progredir bem o suficiente por conta de não conseguir o .jar das telas. Pode me dizer onde achar? ou até me mandar de alguma forma..
é noiss

**Comment by jpalvesloiola** [comment]
Cara, esse .jar foi um sufoco para achar e para configurar. E para ser sincero eu nem me lembro mais onde achei ele kk. Mas vou ver se consigo te ajudar... Me dá um tempinho?

**Comment by jpalvesloiola** [comment]
Segue o [link ](https://github.com/jpalvesloiola/fj11-contas/tree/main/Banco/out/artifacts/BancoTela) para o .jar da tela.

**Comment by gabilu0** [comment]
Salve mano, muito obrigado.
tô chegando em casa agora assim que pisar em casa vou ligar o not.
te mando uma resposta se conseguir, obrigado de coração.
você é um amigo!!!


Em qua., 28 de fev. de 2024 12:09, João Pedro Alves Loiola <
***@***.***> escreveu:
